<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RepositoryUrl>https://github.com/HouseOfLAN/BeamerPresenterForLanParties</RepositoryUrl>
    <Copyright>Copyright (c) 2026 House of LAN</Copyright>
  </PropertyGroup>
</Project>
