// <auto-generated />
using System;
using BeamerPresenter.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeamerPresenter.Infrastructure.Migrations
{
    [DbContext(typeof(PresenterDbContext))]
    [Migration("20260920182541_AddPresenterDisplaySettings")]
    partial class AddPresenterDisplaySettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("BeamerPresenter.Domain.MediaFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeSubdirectories")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("MediaFolders");
                });

            modelBuilder.Entity("BeamerPresenter.Domain.PresenterSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AggressiveTopmost")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowLanAccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlwaysOnTop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("ChromePath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("FfprobePath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaFolder")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("MonitorDeviceName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreventDisplaySleep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("PreventSystemSleep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("WebPort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("BeamerPresenter.Domain.VideoAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AudioChannels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioCodec")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Container")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("FrameRate")
                        .HasColumnType("REAL");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastScannedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastWriteUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaybackStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProbeError")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProbeStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoCodec")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("VideoHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VideoWidth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FullPath")
                        .IsUnique();

                    b.ToTable("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
